version: '2'

services:
   db:
     image: mysql:5.5
     volumes:
       - /root/my_wordpress/mysql:/var/lib/mysql
     restart: always
     mem_limit: 256M
#     environment:
#       MYSQL_ROOT_PASSWORD: wordpress
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wordpress
#       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /root/my_wordpress/html:/var/www/html
     ports:
       - "8000:80"
     restart: always
     mem_limit: 256M
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress