version: '2'

services:
   nginx:
     image: nginx:1.12.1
     volumes:
       - $PWD/my_nginx/www:/www
       - $PWD/my_nginx/nginx:/etc/nginx
       - $PWD/my_nginx/logs:/wwwlogs
     restart: always
     ports:
       - "80:80"
       - "443:443"
     command: [nginx-debug, '-g', 'daemon off;']