version: '2'

services:
   db:
     image: nginx:stable
     volumes:
       - $PWD/my_nginx/www:/www
       - $PWD/my_nginx/conf/nginx.conf:/etc/nginx/nginx.conf
       - $PWD/my_nginx/logs:/wwwlogs
     restart: always
     ports:
       - "80:80"